src/Zendesk/API/Http.php
src/Zendesk/API/Search.php
tests/Zendesk/API/Tests/SearchTest.php

So trying this code:
```
$zendesk = new ZendeskAPI('acquia', $zendesk_creds['email']);
$zendesk->setAuth('token', $zendesk_creds['token']);
$query = 'status<solved+type:ticket';
$params = array(
'query' => $query
);
$search = $zendesk->search($params);
```
throws this error:
```
Invalid search: Invalid status type: solved+type:ticket
```
It looks like the http_build_query call in HTTP::send is encoding the query in a way the API isn't expecting. 
I've added code to check if $json is an array in HTTP::send, and only in that case will http_build_query be called. This allows functions that call HTTP::send encode the GET params themselves, which I used to fix the issue with Search::performSearch.
It should be noted that the actual query I'm making is quite long, and this is the only way I've …

Fixed bug where http_build_query encoding would remove parts of query strings

---

tests/Zendesk/API/Tests/RequestsTest.php

Check the latest comment message to see if the request update success instead of check the request description. 
@zendesk/archer

change test for request update

---

src/Zendesk/API/Tickets.php

It is currently not possible to search for tickets by external_id, which is extremely important for API integrations (so you can retrieve tickets by their local record id). This patch adds in that capability.

Enable searching for tickets by external_id

---

src/Zendesk/API/Client.php
src/Zendesk/API/SatisfactionRatings.php

New method `Client::satisfactionRatings()` provides access to the SatisfactionRatings API class, which wasn't publicly available.
`SatisfactionRatings::findAll()` now accepts the [documented filter params](https://developer.zendesk.com/rest_api/docs/core/satisfaction_ratings#filter).

Add access to SatisfactionRatings API. Add satisfaction filter params.

---

src/Zendesk/API/Debug.php

This is useful for logging. Conversion happens for lastResponseError if needed since all the other ones will be strings as option is passed in during curl_getinfo() calls.

Adds ability to use Debug class as a string

---

src/Zendesk/API/Users.php
tests/Zendesk/API/LiveTests/UsersTest.php

The current `find` method does not allow using the `external_ids` param as documented at https://developer.zendesk.com/rest_api/docs/core/users#show-many-users
This adds a new method specifically for the `show_many` endpoint.

Add method for `users/show_many.json?external_ids=...`

---

src/Zendesk/API/AuditLogs.php
src/Zendesk/API/Http.php

Not ideal, but a quick win: whenever we get an error response from the API, print debug information and throw an exception. Previously every single time we made a call we were doing the error checking and not providing any information, now we can do it in one place.
Todo: remove manual error checking from every API call… (like I've done with AuditLogs)
cc @miogalang @joseconsador

Print debug info on any failure

---

phpunit.xml.dist
tests/Zendesk/API/LiveTests/BasicTest.php
tests/Zendesk/API/LiveTests/TicketCommentsTest.php
tests/Zendesk/API/LiveTests/TicketsTest.php

Mock the API calls for the Ticket Comment Test. 
Removed tests for checking credentials and auth because it is un needed for mocked calls.
Additionally added some options to make phpunit run a bit faster, and to easier debug errors on test. 
- Jira link: 
- Unit Tests might not run properly (Low)

Mock the API calls for ticket comments tests

---

.travis.yml
tests/Zendesk/API/UnitTests/BasicTest.php
tests/Zendesk/API/UnitTests/DummyResource.php
tests/Zendesk/API/UnitTests/ResourceTest.php
tests/Zendesk/API/UnitTests/TicketCommentsTest.php
tests/Zendesk/API/UnitTests/TicketsTest.php
tests/Zendesk/API/UnitTests/UsersTest.php
tests/Zendesk/API/UnitTests/ViewsTest.php

Moved the tests in LiveTests to the UnitTests folder, for consistency. 
Updated .travis.yml to run the unit tests only.
/cc @miogalang @jwswj @mmolina
- The tests may fail (medium)

Move tests to UnitTests folder

---

src/Zendesk/API/HttpClient.php
src/Zendesk/API/Resources/ResourceAbstract.php
src/Zendesk/API/Resources/TicketComments.php
src/Zendesk/API/Resources/Tickets.php
src/Zendesk/API/Resources/Users.php
src/Zendesk/API/Resources/Views.php
src/Zendesk/API/UtilityTraits/ChainedParametersTrait.php
src/Zendesk/API/UtilityTraits/InstantiatorTrait.php
tests/Zendesk/API/LiveTests/BasicTest.php
tests/Zendesk/API/LiveTests/TicketCommentsTest.php
tests/Zendesk/API/LiveTests/TicketsTest.php
tests/Zendesk/API/LiveTests/UsersTest.php
tests/Zendesk/API/LiveTests/ViewsTest.php

Create new instances of each resource when calling them. 
`$client->tickets()->comments()` would instantiate new classes for `Tickets` and `Comments`. 
This means we do not have to worry about leftover state variables and is better design overall.
Additionally we want to add consistency and always use plural both for the resources class names and when instantiating them.
- Jira link: 
- We might not be able to chain properly (medium)

Change the way we instantiate resources. 

---

src/Zendesk/API/Http.php

Remove var_dump() when an exception is thrown.
Wrap Guzzle exception to our own exception class.
- Medium - Existing classes for v2 that rely on exception handling may work differently

Remove var_dump(), pass Guzzle exception to our own exception class

---

composer.json
composer.lock
src/Zendesk/API/Http.php
src/Zendesk/API/HttpClient.php
src/Zendesk/API/Resources/ResourceAbstract.php
tests/Zendesk/API/UnitTests/BasicTest.php
tests/Zendesk/API/UnitTests/ResourceTest.php
tests/Zendesk/API/UnitTests/TicketCommentsTest.php
tests/Zendesk/API/UnitTests/TicketsTest.php
tests/Zendesk/API/UnitTests/UsersTest.php
tests/Zendesk/API/UnitTests/ViewsTest.php

Updated guzzle to ~v6. This uses the PSR7 standard.
Additionally used the built in mocking mechanism of guzzle instead of an external library
Updating all the existing tests to use the guzzle mokcing mechanism
- Jira link: 
- Requests might not be sent properly (medium)

Update guzzle and mocking to use new guzzle

---

src/Zendesk/API/Exceptions/ApiResponseException.php
src/Zendesk/API/Exceptions/ResponseException.php
src/Zendesk/API/Http.php
src/Zendesk/API/Resources/TicketForms.php
src/Zendesk/API/Resources/Tickets.php
src/Zendesk/API/Resources/Users.php
tests/Zendesk/API/UnitTests/BasicTest.php
tests/Zendesk/API/UnitTests/ResourceTest.php
tests/Zendesk/API/UnitTests/TicketFormsTest.php

Make the exception class display the actual errors returned from the API
This gives more readability to the thrown error.
Sample exception:
- Jira link: https://zendesk.atlassian.net/browse/MI-168
- Medium - The API or codebase might return an error that is not in the expected json format

[MI-168] Make exception class display the actual errors returned from the API

---

phpunit.xml.dist
src/Zendesk/API/Exceptions/AuthException.php
src/Zendesk/API/Http.php
src/Zendesk/API/HttpClient.php
src/Zendesk/API/Resources/TicketForms.php
tests/Zendesk/API/LiveTests/AuthTest.php
tests/Zendesk/API/LiveTests/BasicTest.php
tests/Zendesk/API/UnitTests/BasicTest.php
tests/Zendesk/API/UnitTests/UsersTest.php

Add support for basic authentication and oauth token authentication in the client
Add live tests for checking authentication
- Jira link: https://zendesk.atlassian.net/browse/MI-105
- We might not be able to authenticate properly with the client (medium)

[MI-105] Add support for authentication with the api client

---

src/Zendesk/API/Tickets.php

Just a simple addition to support the [tickets/create_many.json](https://developer.zendesk.com/rest_api/docs/core/tickets#creating-many-tickets) endpoint.
The new `Tickets::createMany()` method is based on the existing `Tickets::create()` method. The main difference being that it doesn't support attachments.

Added support for creating many tickets

---

.travis.yml

Add retry when installing composer dependencies to prevent composer network errors on travis.
This will retry the command three times before failing.
- Jira link: 
- The travis builds might fail (Low)

Add retry to composer install for dealing with network issues on travis

---

src/Zendesk/API/Http.php
src/Zendesk/API/HttpClient.php
src/Zendesk/API/Resources/Attachments.php
src/Zendesk/API/Resources/ResourceAbstract.php
src/Zendesk/API/Resources/Tickets.php
src/Zendesk/API/Resources/Users.php
tests/Zendesk/API/UnitTests/AttachmentsTest.php
tests/Zendesk/API/UnitTests/BasicTest.php
tests/Zendesk/API/UnitTests/TicketsTest.php

Add uploading of attachments to version 2. Allow uploading of attachments and creating tickets with them.
- Jira link: https://zendesk.atlassian.net/browse/MI-111
- Ticket attachments might fail (medium)

[MI-111] Allow user to upload an attachment

---

src/Zendesk/API/BulkTraits/BulkCreateTrait.php
src/Zendesk/API/BulkTraits/BulkDeleteTrait.php
src/Zendesk/API/BulkTraits/BulkFindTrait.php
src/Zendesk/API/BulkTraits/BulkUpdateTrait.php
src/Zendesk/API/Exceptions/RouteException.php
src/Zendesk/API/HttpClient.php
src/Zendesk/API/Resources/Automations.php
src/Zendesk/API/Resources/Groups.php
src/Zendesk/API/Resources/HelpCenter/Categories.php
src/Zendesk/API/Resources/Macros.php
src/Zendesk/API/Resources/ResourceAbstract.php
src/Zendesk/API/Resources/TicketAudits.php
src/Zendesk/API/Resources/TicketComments.php
src/Zendesk/API/Resources/TicketForms.php
src/Zendesk/API/Resources/Tickets.php
src/Zendesk/API/Resources/Triggers.php
src/Zendesk/API/Resources/Users.php
src/Zendesk/API/Resources/Views.php
tests/Zendesk/API/UnitTests/DummyResource.php
tests/Zendesk/API/UnitTests/MacrosTest.php
tests/Zendesk/API/UnitTests/ResourceTest.php
tests/Zendesk/API/UnitTests/TicketAuditsTest.php
tests/Zendesk/API/UnitTests/TicketCommentsTest.php
tests/Zendesk/API/UnitTests/TicketsTest.php
tests/Zendesk/API/UnitTests/UsersTest.php

Adds traits for bulk actions. This way special cases can be handled individually.
Adds another wrapper for http requests under HttpClient . This serves to reduce repetition in some methods that only require a change in endpoint, so we don't have to call the ResourceAbstract methods like create() or find() . Instead $this->client->post() / get() / delete() / put() can be used.
- Jira link: 
- High - query parameters may not get passed to the api request

Add bulk traits

---

src/Zendesk/API/HttpClient.php
src/Zendesk/API/Resources/AuditLogs.php
src/Zendesk/API/Resources/ResourceAbstract.php
tests/Zendesk/API/UnitTests/AuditLogsTest.php

Allow the client to use the audit logs resource
- Jira link: https://zendesk.atlassian.net/browse/MI-112
- We might not be able to use the audit logs endpoints (low)

[MI-112] Allow the client to use the audit logs resource

---

src/Zendesk/API/BulkTraits/BulkUpdateTrait.php
src/Zendesk/API/Http.php
src/Zendesk/API/Resources/Users.php
src/Zendesk/API/UtilityTraits/ChainedParametersTrait.php
tests/Zendesk/API/UnitTests/BasicTest.php
tests/Zendesk/API/UnitTests/UsersTest.php

Allow the user to update user profile photo with the api client.
This separates the updating by specifying a file and uploading it, and updating from a remote url.
- Jira link: https://zendesk.atlassian.net/browse/MI-107
- The user might not be able to update his profile image (Low)

[MI-107] Allow user to update profile photo using client

---

src/Zendesk/API/Http.php
src/Zendesk/API/HttpClient.php
src/Zendesk/API/Utilities/Auth.php
tests/Zendesk/API/UnitTests/AuthTest.php

Move the auth operations to utility class
Add unit test for auth
- Jira link: https://zendesk.atlassian.net/browse/MI-105
- We might not be able to make authenticated calls with the client (High)

[MI-105] Move Auth operations to it's own utility class

---

src/Zendesk/API/HttpClient.php
src/Zendesk/API/Resources/OrganizationFields.php
tests/Zendesk/API/UnitTests/OrganizationFieldsTest.php

Add the organization fields resource so it can be used with the client
- Jira link: https://zendesk.atlassian.net/browse/MI-135
- We might not be able to call the organization resource endpoints using the client (low)

[MI-135] Add organization fields resource

---

src/Zendesk/API/HttpClient.php
src/Zendesk/API/Resources/OAuthClients.php
tests/Zendesk/API/UnitTests/OAuthClientsTest.php

Add the oauth clients resource so we can call the endpoints using the client.
* JIRA: https://zendesk.atlassian.net/browse/MI-126
* Low. We might not be able to call the OAuth clients endpoints using the client.

[MI-127] Add the oauth clients resource

---

src/Zendesk/API/HttpClient.php
src/Zendesk/API/Resources/TwitterHandles.php
tests/Zendesk/API/UnitTests/TwitterHandlesTest.php

Add twitter handles resource and test
- Jira link: https://zendesk.atlassian.net/browse/MI-123
- Low. We might not be able to use the Monitored Twitter Handles resources

[MI-133] Add Monitored Twitter Handles

---

tests/Zendesk/API/UnitTests/AppInstallationsTest.php
tests/Zendesk/API/UnitTests/AttachmentsTest.php
tests/Zendesk/API/UnitTests/AuditLogsTest.php
tests/Zendesk/API/UnitTests/AutomationsTest.php
tests/Zendesk/API/UnitTests/DynamicContentItemVariantsTest.php
tests/Zendesk/API/UnitTests/GroupsTest.php
tests/Zendesk/API/UnitTests/LocalesTest.php
tests/Zendesk/API/UnitTests/MacrosTest.php
tests/Zendesk/API/UnitTests/OAuthClientsTest.php
tests/Zendesk/API/UnitTests/OAuthTokensTest.php
tests/Zendesk/API/UnitTests/OrganizationFieldsTest.php
tests/Zendesk/API/UnitTests/OrganizationMembershipsTest.php
tests/Zendesk/API/UnitTests/OrganizationSubscriptionsTest.php
tests/Zendesk/API/UnitTests/OrganizationsTest.php
tests/Zendesk/API/UnitTests/RequestCommentsTest.php
tests/Zendesk/API/UnitTests/RequestsTest.php
tests/Zendesk/API/UnitTests/ResourceTest.php
tests/Zendesk/API/UnitTests/SearchTest.php
tests/Zendesk/API/UnitTests/TagsTest.php
tests/Zendesk/API/UnitTests/TicketAuditsTest.php
tests/Zendesk/API/UnitTests/TicketCommentsTest.php
tests/Zendesk/API/UnitTests/TicketFieldsTest.php
tests/Zendesk/API/UnitTests/TicketsTest.php
tests/Zendesk/API/UnitTests/TriggersTest.php
tests/Zendesk/API/UnitTests/UserFieldsTest.php
tests/Zendesk/API/UnitTests/UserIdentitiesTest.php
tests/Zendesk/API/UnitTests/UsersTest.php
tests/Zendesk/API/UnitTests/ViewsTest.php

Use a wrapper function to assert the API client functionality. This removes a lot of repetitive test code.
- Jira link: 
- Medium - the tests might not cover all cases

Use BasicTest::assertEndpointCalled() for most mocked tests

---

src/Zendesk/API/Resources/Core/AppInstallationLocations.php
src/Zendesk/API/Resources/Core/Apps.php
tests/Zendesk/API/UnitTests/AppInstallationLocationsTest.php

Add app installation locations resource
This is dependent on https://github.com/zendesk/zendesk_api_client_php/pull/144
* JIRA: https://zendesk.atlassian.net/browse/MI-146
* Low. We might not be able to call the app installation endpoints using the client

[MI-146] Add the app install locations resource

---

src/Zendesk/API/HttpClient.php
src/Zendesk/API/Resources/Core/PushNotificationDevices.php
src/Zendesk/API/Resources/PushNotificationDevices.php
tests/Zendesk/API/UnitTests/PushNotificationDevicesTest.php

Allow the client to use the push notification devices resource
* JIRA: https://zendesk.atlassian.net/browse/MI-150
* Low. We might not be able to call push notification devices endpoints using the client

[MI-150] Add the push notifications devices resource

---

src/Zendesk/API/Resources/Core/Organizations.php
tests/Zendesk/API/UnitTests/Core/OrganizationMembershipsTest.php

Rename the subresource of OrganizationMemberships in the Organization class.
The call will now look like this
`$client->organizations(1)->memberships()->findAll();`
* JIRA: https://zendesk.atlassian.net/browse/MI-177
* Low. We might not be able to call the organization membership correctly.

[MI-177] Rename the subresource of OrganizationMemberships in the Organization

---

README.md

Add PHP version support to the README.
PHP5.5+ is a requirement for Guzzle 6.
- Jira link: https://zendesk.atlassian.net/browse/MI-179
- None

[MI-179] Add PHP version support to the README

---

README.md

Quick update to add some syntax highlighting to the code snippets and examples :) To compare:
https://github.com/zendesk/zendesk_api_client_php/blob/a22dec5794c1bd7c3f6b64e8db22a93a60ae634f/README.md
vs
https://github.com/zendesk/zendesk_api_client_php/blob/831cf707d71759b0688e2105e2e95ef20c6fbe74/README.md

Delete trailing spaces from readme, add syntax highlighting

---

composer.json

I noticed on https://packagist.org/packages/zendesk/zendesk_api_client_php that our php dependency was wrong. 
@miogalang @joseconsador 
- Composer screws up [low]

Update php dependency for composer

---

src/Zendesk/API/Exceptions/ApiResponseException.php

I was struggling to debug some errors earlier today because the messages being returned weren't useful:
```
Fatal error: Uncaught exception 'Zendesk\API\Exceptions\ApiResponseException' with message '
Errors: ' in /Users/jsmale/Code/other/testphpapi/vendor/zendesk/zendesk_api_client_php/src/Zendesk/API/Http.php:116
Stack trace:
#0 /Users/jsmale/Code/other/testphpapi/vendor/zendesk/zendesk_api_client_php/src/Zendesk/API/HttpClient.php(408): Zendesk\API\Http::send(Object(Zendesk\API\HttpClient), 'tickets/155.jso...', Array)
#1 /Users/jsmale/Code/other/testphpapi/vendor/zendesk/zendesk_api_client_php/src/Zendesk/API/Traits/Resource/Update.php(40): Zendesk\API\HttpClient->put('tickets/155.jso...', Array)
#2 /Users/jsmale/Code/other/testphpapi/vendor/zendesk/zendesk_api_client_php/src/Zendesk/A …
```

Change the exception message format

---

src/Zendesk/API/Http.php
tests/Zendesk/API/UnitTests/Core/UsersTest.php

@miogalang @joseconsador @iandjx @joho 
Quick fix for https://github.com/zendesk/zendesk_api_client_php/issues/195 while we work through the bigger change.

Whitelist external_id as an accepted query param

---

.travis.yml

Add PHP7 into the build matrix, allowing it to fail for now.
@miogalang @joseconsador 
- None

Add php7 into the build matrix

---

samples/oauth.php
src/Zendesk/API/Http.php
src/Zendesk/API/HttpClient.php
src/Zendesk/API/Resources/Core/AuditLogs.php
src/Zendesk/API/Resources/Core/Organizations.php
src/Zendesk/API/Resources/Core/Tickets.php
src/Zendesk/API/Resources/Core/Users.php
src/Zendesk/API/Resources/Core/Views.php
tests/Zendesk/API/LiveTests/SearchTest.php
tests/Zendesk/API/LiveTests/TicketsTest.php
tests/Zendesk/API/LiveTests/UsersTest.php
tests/Zendesk/API/UnitTests/Core/AuditLogsTest.php
tests/Zendesk/API/UnitTests/Core/ResourceTest.php
tests/Zendesk/API/UnitTests/Core/UsersTest.php
tests/Zendesk/API/UnitTests/Core/ViewsTest.php

Removes the HttpClient::prepareQueryParams() method which filters the allowed query parameters (iterators usually) for most requests. 
/cc @miogalang @jwswj @mmolina @iandjx 
- Jira link: https://zendesk.atlassian.net/browse/MI-258
- Github Issue: #195 
- High: Query parameters may not be set / ANY query parameter may be set. Could break calls to the API.

[MI-258] User search

---

src/Zendesk/API/Exceptions/ApiResponseException.php
src/Zendesk/API/Http.php
tests/Zendesk/API/LiveTests/TicketsTest.php
tests/Zendesk/API/UnitTests/Core/ResourceTest.php

Fixes the fatal error from #201 .
The response object from the ResponseException is NULL, which causes this error.
Instead of getting the fatal error, an exception in the following format will be received instead.
```
Zendesk\API\Exceptions\ApiResponseException: Error completing request [url] http://foo.com [http method] GET
```
Uses Guzzle's RequestException::create() method to generate the exceptions, below is a sample of a ClientException.
```
Zendesk\API\Exceptions\ApiResponseException: Client error response [url] https://z3njosemanila.zendesk.com/api/v2/tickets/99999999.json [http method] GET [status code] 404 [reason phrase] Not Found [details] {"error":"RecordNotFound","description":"Not found"}
```
Added a test for handling situations where the server returns no response or the …

Use guzzle's exception message

---

src/Zendesk/API/Resources/Core/Tickets.php
tests/Zendesk/API/UnitTests/Core/TicketsTest.php

Add support for merging tickets endpoint
https://developer.zendesk.com/rest_api/docs/core/tickets#merge-tickets-into-target-ticket
Solves ticket: https://support.zendesk.com/agent/tickets/1253489
/cc @jwswj @joseconsador @iandjx @pdeuter @mmolina @ggrossman 
* JIRA: https://zendesk.atlassian.net/browse/MI-320
* Medium. We might not be able to merge tickets using the API.

[MI-320] Add support for ticket merging.

---

src/Zendesk/API/HttpClient.php

Add the ticket fields resource to the Http Client. It was previously missing and not accessible.
/cc @zendesk/butanding
* JIRA: https://zendesk.atlassian.net/browse/MI-332
* Medium. We might not be able to access the ticket fields resource

[MI-332] Add the missing ticket fields resource to the Http Client

---

src/Zendesk/API/Resources/Core/Users.php

https://github.com/zendesk/zendesk_api_client_php/issues/208 describes the issue at hand. The $params don't get passed through successfully.
/cc @zendesk/quokka
- Jira link: 
- None

Please pass the params array to the parent function call

---

src/Zendesk/API/Exceptions/ApiResponseException.php

Adds the request body to the exception message, in cases where no response is returned from the API call.
/cc @miogalang @jwswj @mmolina @iandjx @pdeuter
- Jira link: 
- None

Add request body to exception message

---

composer.json

Packagist will just get the version from the github tag. Currently this takes precedence and thus some of our releases are not appearing.
Fix for https://github.com/zendesk/zendesk_api_client_php/issues/211
/cc @zendesk/butanding @mmolina
* JIRA:
* Medium. We might be missing versions in packagist.

Remove the composer version from composer.json

---

src/Zendesk/API/Resources/Core/OrganizationTickets.php
src/Zendesk/API/Resources/Core/Organizations.php
tests/Zendesk/API/UnitTests/Core/OrganizationTicketsTest.php

You can now load the tickets for a specific organization, based on the existing API-end-point. (https://developer.zendesk.com/rest_api/docs/core/tickets#listing-tickets)

Added the possibility to load tickets for a specific organization

---

src/Zendesk/API/Http.php
src/Zendesk/API/HttpClient.php
tests/Zendesk/API/UnitTests/Core/ResourceTest.php

Add option to set additional headers to the client. Initial use-case for this is to keep track of requests made per integration.
/cc @zendesk/mintegrations @mmolina @miketineo
- Jira link: https://zendesk.atlassian.net/browse/MI-331
- Medium: default headers could be overwritten and unexpected responses/requests could be sent.

[MI-331] Add option to set additional headers to the client

---

src/Zendesk/API/Resources/Core/Requests.php
src/Zendesk/API/Resources/Core/SatisfactionRatings.php

When you create a satisfaction rating, with:
```
$client->satisfactionRatings()->create([
'score' => 'Good',
'comment' => 'Awesome support!',
'ticket_id' => 33,
]);
```
You reiceive an "InvalidEnpoint", because the request is done to https://{subdomain}.zendesk.com/api/v2/satisfaction_ratings.json instead of https://{subdomain}.zendesk.com/api/v2/tickets/{ticket_id}/satisfaction_rating.json as explained [here](https://developer.zendesk.com/rest_api/docs/core/satisfaction_ratings#create-a-satisfaction-rating).
This file change fixes the issue for me.

Satisfaction rating - invalid endpoint

---

src/Zendesk/API/Resources/Core/SatisfactionRatings.php
src/Zendesk/API/Resources/Core/Tickets.php
tests/Zendesk/API/UnitTests/Core/SatisfactionRatingsTest.php

Add tests for Satisfaction Rating creation
Update the Docblock
Allow it to be chained from the ticket resource
/cc @zendesk/mintegrations @mmolina @miketineo
- Jira link: https://zendesk.atlassian.net/browse/MI-480
- Medium. We might not be able to create satisfactions ratings using the client

[MI-480] Update CSAT rating creation to be chainable with ticket.

---

src/Zendesk/API/Resources/Core/AuditLogs.php
tests/Zendesk/API/UnitTests/Core/AuditLogsTest.php

The documentation for Audit Logs (https://developer.zendesk.com/rest_api/docs/core/audit_logs) incorrectly used to state that filter parameters looked like this:
```
?filter["source_type"]=user
?filter["source_type"]=rule
?filter["created_at"]=2013-01-01%2000:00:00,2013-01-01%2023:59:59
```
Based on that information, the PHP code was enforcing this format with the double-quotes present.
However, the API doesn't actually work like that!
What actually works looks like this:
```
By source type:
?filter[source_type]=user
?filter[source_type]=rule
By exact source:
?filter[source_type]=user&filter[source_id]=123
By actor:
?filter[actor_id]=123
By IP address:
?filter[ip_address]=127.0.0.1
By time of creation:
?filter[created_at][]=2013-01-01T00:00:00Z&filter[created_at][]=2013-01-01T23:59:59Z …
```

Fix Audit Logs filtering for correct filter parameter specification

---

src/Zendesk/API/Utilities/OAuth.php
tests/Zendesk/API/UnitTests/Utilities/OAuthTest.php

Fixes a problem where the defined domain is not used when generating authentication links.
* JIRA: 
* Medium. We might generate wrong auth links.

Use the domain defined in client when getting the urls for domain

---

src/Zendesk/API/Http.php

json_decode() returns an object if second argument is not being set to true.

Fixed returning type declaration

---

src/Zendesk/API/Resources/Core/DynamicContentItemVariants.php
src/Zendesk/API/Resources/Core/Organizations.php
src/Zendesk/API/Resources/Core/Tickets.php
src/Zendesk/API/Traits/Resource/CreateOrUpdateMany.php
tests/Zendesk/API/LiveTests/TicketsTest.php
tests/Zendesk/API/LiveTests/UsersTest.php
tests/Zendesk/API/UnitTests/Core/ResourceTest.php

Remove create and update many to classes which don't have it.
Fix method to POST as the docs say (https://developer.zendesk.com/rest_api/docs/core/users#create-or-update-many-users)
Add unit test
Update live test for new delete response
* JIRA: https://zendesk.atlassian.net/browse/MI-575
* Low. Client might not be able to call the create or update many endpoint

[MI-575] Add unit tests and cleanup create and update many

---

README.md
samples/getTickets.php

company.com exists in reality.
https://whois.icann.org/en/lookup?name=company.com
we should use example.com instead.
http://www.rfc-editor.org/rfc/rfc2606.txt

use example.com for sample codes

---

src/Zendesk/API/Resources/Core/AppInstallations.php
tests/Zendesk/API/UnitTests/Core/AppInstallationsTest.php

Fix update of app installations to allow setting of "enabled"
see: https://developer.zendesk.com/rest_api/docs/core/apps#update-an-app-installation
* JIRA: https://zendesk.atlassian.net/browse/MI-753
* Medium. Users might not be able to call the update app installation endpoint

[MI-753] Fix update of app installations to allow setting of "enabled"

---

src/Zendesk/API/Resources/Core/TicketComments.php

/cc @zendesk/sustaining @zendesk/mintegrations
Fixes a typo in an error message
* ZD ticket: https://support.zendesk.com/agent/tickets/1879279
*  None: no functional change

[ZD#1945658] Fix typo in error message

---

tests/Zendesk/API/LiveTests/TicketsTest.php

Add a live test to check if a ticket created with a `group_id` is actually assigned to the correct group. 
* Issue: https://github.com/zendesk/zendesk_api_client_php/issues/288
* none

add live test to check if ticket is assigned to group

---

README.md
samples/tickets/createTicket.php
samples/tickets/createTicketWithAttachment.php
samples/tickets/deleteTicket.php
samples/tickets/getTicketComments.php
samples/tickets/getTickets.php
samples/tickets/qcreateTicket.php
samples/tickets/searchTickets.php
samples/tickets/updateTicket.php
samples/tickets/viewTicket.php

There has been a lot of complaints of error requests in examples. Was not able to replicate the problem as it may be a development setup issue. This outputs the actual message from the thrown exception to help users debug the issue. Also updated readme on how to install using composer.
* Composer installation problem https://github.com/zendesk/zendesk_api_client_php/issues/279
* Error request completion https://github.com/zendesk/zendesk_api_client_php/issues/289, https://github.com/zendesk/zendesk_api_client_php/issues/264, and https://github.com/zendesk/zendesk_api_client_php/issues/248
* none

Outputs message from exception and updated README

---

src/Zendesk/API/HttpClient.php
src/Zendesk/API/Resources/Core/Tickets.php
src/Zendesk/API/Traits/Resource/Create.php
tests/Zendesk/API/UnitTests/Core/TicketsTest.php

Allows the creation of tickets asynchronously.
ref: https://developer.zendesk.com/rest_api/docs/core/tickets#create-ticket-asynchronously
* JIRA: 
* medium. Ticket creation mught fail

Allow async query parameter for creating tickets

---

src/Zendesk/API/Http.php

In the documentation from Guzzle, it is indicated that you can simply cast the getBody() to a string to use the response. The method getContents() will only read the remaining contents if a previous read() is performed.
see: http://docs.guzzlephp.org/en/latest/quickstart.html?#using-responses
This causes problems if you install a Guzzle Log middleware. This will read the body causing getContents() te become empty.

Remove getContents()

---

src/Zendesk/API/Traits/Resource/DeleteMany.php

Fixes IDE type inspection warnings on response fields access:
```php
$response = $client->organizationMemberships()->deleteMany($bulk_delete);
print_r($response->job_status);
```

minor: fix doc hint of DeleteMany return type

---

src/Zendesk/API/Http.php
tests/Zendesk/API/UnitTests/HttpTest.php

Underlying error message from curl are being lost because the original execption is not being passed along to the exception wrappers.
Previous exceptions that are returned as
```
PHP Fatal error: Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'Error completing request' in /var/www/sites/zendesk_api_client_php/vendor/guzzle/src/Exception/RequestException:71
```
should now look more informative. In the case of a curl SSL error, this will now look like:
```
PHP Fatal error: Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 1: Protocol "https" not supported or disabled in libcurl (see http://curl.haxx.se.libcurl/c/libcurl-errors.html)' in /var/ww/sites/zendesk_api_client_php/vendor/guzzlehttp/guzzle/src/handl …
```

Pass previous exception so that we don't lose it's message body

---

src/Zendesk/API/Http.php
src/Zendesk/API/Resources/Core/Attachments.php
src/Zendesk/API/Traits/Resource/MultipartUpload.php
tests/Zendesk/API/UnitTests/BasicTest.php
tests/Zendesk/API/UnitTests/Core/AttachmentsTest.php
tests/Zendesk/API/UnitTests/Core/ResourceTest.php

I needed the upload and multipart upload to support any PSR-7 stream.
This gives a lot of flexibility for instance now we can create a PSR-7 stream out of in-memory content and upload the content as an attachment.
I committed the modification independent of each-other so that you might cherry pick them if necessary but feel free to squash them.

File upload stream

---

tests/Zendesk/API/UnitTests/VersionTest.php

Add test to check consistent version to avoid instances where the version class constant in the [HttpClient class](https://github.com/zendesk/zendesk_api_client_php/blob/89630494acaad3515622e7fa2153b7a9ac9f77e5/src/Zendesk/API/HttpClient.php#L108) and the version [file](https://github.com/zendesk/zendesk_api_client_php/blob/89630494acaad3515622e7fa2153b7a9ac9f77e5/VERSION#L1) becomes different.
* JIRA: https://zendesk.atlassian.net/browse/MI-1512
* Issue: https://github.com/zendesk/zendesk_api_client_php/issues/312
* [low] Virtually none, just added a new test.

[MI-1512] Add test to check consistent version

---

README.md
src/Zendesk/API/HttpClient.php
src/Zendesk/API/Middleware/RetryHandler.php
tests/Zendesk/API/UnitTests/BasicTest.php
tests/Zendesk/API/UnitTests/Middleware/RetryHandlerTest.php

* add guzzle middleware `RetryHandler`
* made retrying of ssl issue a default behaviour
* JIRA: https://zendesk.atlassian.net/browse/MI-1724
* [low] might slow down api especially on parts that will trigger retries

[MI-1724] retry ssl issues by default

---

src/Zendesk/API/Resources/Core/Tags.php
tests/Zendesk/API/LiveTests/TicketsTest.php

Set Tags resource object name to prevent magically singularizing it.
* JIRA: https://zendesk.atlassian.net/browse/MI-1783
* Issue: #343 
* [Low] A 'tag' return value could be returned and may not be read by the client in the future, because objectName is plural.

[MI-1783] Set Tags resource object name

---

src/Zendesk/API/HttpClient.php
src/Zendesk/API/Resources/Chat.php
src/Zendesk/API/Resources/Chat/Apps.php
src/Zendesk/API/Resources/Chat/ResourceAbstract.php
tests/Zendesk/API/UnitTests/Chat/AppsTest.php

Add additional resource  for installing Chat apps.
```
$this->client->chat->apps()->install($postFields);
```
which POSTs to the `api/chat/apps/installations.json` endpoint as opposed to the `api/v2/apps/installations.json` for ZendeskSupport apps.
* JIRA: https://zendesk.atlassian.net/browse/MI-1397
* [low] Adds a new resource. Could cause some confusion between this and the [regular apps installation endpoint](https://developer.zendesk.com/rest_api/docs/core/apps#list-app-installations)

[MI-1397] Add resource to support installing chat apps.

---

src/Zendesk/API/Resources/Core/OrganizationMemberships.php
src/Zendesk/API/Resources/Core/PushNotificationDevices.php
src/Zendesk/API/Resources/Core/Users.php
tests/Zendesk/API/UnitTests/Core/AppInstallationsTest.php
tests/Zendesk/API/UnitTests/Core/DynamicContentItemVariantsTest.php
tests/Zendesk/API/UnitTests/Core/OrganizationMembershipsTest.php
tests/Zendesk/API/UnitTests/Core/OrganizationTicketsTest.php
tests/Zendesk/API/UnitTests/Core/ResourceTest.php
tests/Zendesk/API/UnitTests/Core/TicketCommentsTest.php

* run `vendor/bin/phpcbf --extensions=php --standard=PSR2 --report=summary -np src/ tests/` to fix phpcs errors. I guess PSR2 got stricter.
* PR that failed due to phpcs: https://github.com/zendesk/zendesk_api_client_php/pull/341
* [low] might still fail in the future if criteria becomes more stricter

run vendor/bin/phpcbf to fix vendor/bin/phpcs

---

src/Zendesk/API/Attachments.php

`$params['name']` is sometimes not set and causes an undefined index error.

Fix undefined index error

---

src/Zendesk/API/Http.php

Without this option set, this is a security vulnerability where the remote server can respond with a non-http protocol such as FTP for example, and curl will happily just follow the redirect.
This needs applying to the V2 track also.

Add CURLOPT_PROTOCOLS = CURLPROTO_HTTP | CURLPROTO_HTTPS

---

samples/helpcenter/createArticles.php
src/Zendesk/API/Resources/HelpCenter/Articles.php
src/Zendesk/API/Resources/HelpCenter/Sections.php
tests/Zendesk/API/UnitTests/HelpCenter/ArticlesTest.php

This patch adds support for Article creation via chaining, e.g.:
$article = $client->helpCenter->sections($sectionId)->articles()->create([
'locale' => 'en-us',
'title' => 'Smartest Fish in the World',
]);
The unit tests pass. I had some trouble running the "Live" tests against a Sandbox instance.
My team is relatively new to this code base, so I apologize in advance if any of this is off! Creation via chaining *seemed* to be the expected implementation.

Implement HelpCenter Article creation

---

composer.json

/cc @zendesk/mintegrations 
Update license identifier. When running `composer validate` we get the following notice.
```
./composer.json is valid, but with a few warnings
See https://getcomposer.org/doc/04-schema.md for details on the schema
License "Apache License Version 2.0" is not a valid SPDX license identifier, see https://spdx.org/licenses/ if you use an open license.
If the software is closed-source, you may use "proprietary" as license.
```
* Github issue: https://github.com/composer/packagist/issues/858#issuecomment-359272204
* [none]

Update license identifier

---

.travis.yml

Adding PHP 7.1, 7.2 and nightly to build matrix.
Removed PHP 7.0 from the `allow_failures` since it passes.  PHP 7.2 and nightly do not pass currently, so adding those to `allow_failures`.
Added the `fast_finish` setting so that builds return quicker regardless if the `allow_failures` builds pass or not (https://blog.travis-ci.com/2013-11-27-fast-finishing-builds).

Updating Travis PHP build matrix

---

.travis.yml

This will fix php 5.5 issues with `xenial`  This will update the dist to `trusty`
* https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment
* https://travis-ci.community/t/php-5-4-and-5-5-archives-missing/3723
* Low: Whole test suite will now run on trusty.

Use trusty to run tests for php 5.5

---

src/Zendesk/API/Utilities/OAuth.php

Validate the provided Zendesk subdomain to be a valid subdomain in:
- getAuthUrl
- getAccessToken

Validate the provided Zendesk subdomain

---

composer.json

This package uses functions from `guzzlehttp/psr7`, which are removed in psr7 2.0. As no dependency was declared, it was possible to install psr7 2.0 together with this package, resulting in fatal errors. By declaring the dependency, we can limit psr7 to 1.x.
After #469 is merged, the version constraint can be updated to `^1.7 || ^2.0` (as the static method API used in that PR was introduced in 1.7.0).

Declare dependency on guzzlehttp/psr7

---

src/Zendesk/API/HttpClient.php

`call_user_func_array()` is used by `HttpClient::getSideload(array $params = [])`,  and since PHP 8^  introduced named arguments, the use of an associative array as arguments, will break the code since the array_merge does not support named arguments.
The fix is changing this line:
https://github.com/zendesk/zendesk_api_client_php/blob/b451b743d9d6d81a9abf7cb86e70ec9c5332123e/src/Zendesk/API/HttpClient.php#L441
To this:
```
return call_user_func_array('array_merge', array_values($sideloads));
```

Fix PHP 8 introduced breaking change to call_user_func_array()

---

src/Zendesk/API/Http.php
src/Zendesk/API/Utilities/OAuth.php

`\GuzzleHttp\Psr7\stream_for` has been deprecated, `GuzzleHttp\Psr7\Utils::streamFor()` is the replacement method, and has been replaced below. 
https://docs.aws.amazon.com/aws-sdk-php/v3/api/function-GuzzleHttp.Psr7.stream_for.html

change stream_for() to Utils::streamFor() to retain Guzzle 7.2 compatibility 

---

src/Zendesk/API/Resources/Core/Translations.php
src/Zendesk/API/Resources/ResourceAbstract.php
tests/Zendesk/API/UnitTests/Core/TranslationsTest.php

**Goal of this PR:**
[laravel-i18n-command](https://github.com/zendesk/laravel-i18n-command ) is a translation library that uses this library to pull down translations files in json format. As we move the endpoint 
from: https://support.zendesk.com/api/v2/locales/en.json?include=translations&packages=slack-auth-service
to: https://static.zdassets.com/translations/slack-auth-service/manifest.json
This is a need to specify the domain and resources to be other than `api/v2`. 
We want to be able to do this:
```
$this->client->translations()->find();
```
to return back the contents of the manifest file for a particular service such as `slack-auth-service`.

Add `Translations` as a resource name and be able to specify the apiBaseUrl

---

composer.json

With #469 being merged, this package now supports 1.7+ and 2.0

Allow guzzlehttp/psr7 2.0

---

src/Zendesk/API/Resources/Core/Users.php

The method tickets was not exposed in the User class. For this reason PHPStorm and PHPStan had issues with this class.

will update the PHPDoc block to add the @method tickets() to the User class

---

CBP_UPGRADE_GUIDE.md
README.md
UPGRADE_GUIDE.md
docker-compose.yml
src/Zendesk/API/Http.php
src/Zendesk/API/Traits/Utility/Pagination/PaginationIterator.php
tests/Zendesk/API/UnitTests/Traits/Utility/PaginationIteratorTest.php

* Allows lib consumers to define what method they want to call for their iterator
* Better docs on upgrading

RED-2002 Iterator Associations
