- tests/Zendesk/API/UnitTests/GroupsTest.php
Added Unit Test for Groups with a Mock Object so the test is not dependent on live HTTP Requests
> Added Unit Test for Groups with Mocking

- src/Zendesk/API/Client.php
- src/Zendesk/API/Debug.php
- src/Zendesk/API/DynamicContent.php
- src/Zendesk/API/Http.php
- src/Zendesk/API/Search.php
- src/Zendesk/API/Users.php
- tests/Zendesk/API/LiveTests/DynamicContentTest.php
- tests/Zendesk/API/LiveTests/SearchTest.php
- tests/Zendesk/API/LiveTests/UsersTest.php
See commit messages, it's all documented there!
Would be great to get this to master + composer package asap, for we need the fixes to go live!
> Fixed users()->merge, new endpoint dynamicContent, improvement for debug error response, fix search

- composer.json
- src/Zendesk/API/Http.php
Fix bugs for uploading with `filename` and `body`
@zendesk/archer
> Fix bugs for uploading

- src/Zendesk/API/Organizations.php
- tests/Zendesk/API/UnitTests/OrganizationsTest.php
added Unit Tests with Mock - Group Memberships and Organizations
changed Organizations->CreateMany() to use Plural Object rather than Single Object because the method was failing.
> added Unit Tests with Mock, Updated Organizations Endpoint

- src/Zendesk/API/Tickets.php
Hi, I've fixed a bug with the listing of problem tickets:
https://developer.zendesk.com/rest_api/docs/core/tickets#listing-ticket-problems
Would be great to get this to > main > composer asap.
Regards,
Hartmut
> ha-quidco: fix problem ticket listing

- src/Zendesk/API/Client.php
- src/Zendesk/API/PushNotificationDevices.php
- tests/Zendesk/API/LiveTests/PushNotificationDevicesTest.php
/cc @ggrossman @shanitang 
This is for an upcoming API call: https://developer.zendesk.com/rest_api/docs/core/push_notification_devices
> Add support for the Push Notifications Devices destroy_many call.

- src/Zendesk/API/Users.php
- tests/Zendesk/API/LiveTests/UsersTest.php
Add support for `update_many` users by `id`, `external_id`, and batch updating individual users.
@waferbaby @ggrossman
> Add support for update_many users

- .gitignore
- composer.json
- composer.lock
- phpunit.xml.dist
- src/Zendesk/API/AuditLogs.php
- src/Zendesk/API/Client.php
- src/Zendesk/API/Http.php
- tests/Zendesk/API/LiveTests/BasicTest.php
- tests/Zendesk/API/LiveTests/TicketsTest.php
> First mock tests

- tests/Zendesk/API/LiveTests/BasicTest.php
- tests/Zendesk/API/LiveTests/TicketsTest.php
Move HTTP mock setup to BasicTest class
/cc @miogalang @atroche 
- Jira link: 
- None
> Move HTTP mock setup to BasicTest class

- tests/Zendesk/API/LiveTests/BasicTest.php
- tests/Zendesk/API/LiveTests/UsersTest.php
Mock API calls for UsersTest, cleanup testMerge(), add testCreate() and testDelete() tests.
- Jira link: 
- None
> Mock API calls for UsersTest, cleanup testMerge

- tests/Zendesk/API/LiveTests/TicketAuditsTest.php
Mock the API calls for ticket audit test. Removed unnecessary tests
- Jira link: 
- Tests might fail (low)
> Mock API calls for the ticket audit tests

- tests/Zendesk/API/LiveTests/UsersTest.php
- tests/Zendesk/API/LiveTests/ViewsTest.php
Add ViewsTest, update UsersTest for response code option
> add ViewsTest, update UsersTest for response code option

- .travis.yml
- composer.json
- composer.lock
- index.php
- oauth.php
- src/Zendesk/API/Debug.php
- src/Zendesk/API/Exceptions/CustomException.php
- src/Zendesk/API/Exceptions/MissingParametersException.php
- src/Zendesk/API/Exceptions/ResponseException.php
- src/Zendesk/API/Http.php
- src/Zendesk/API/HttpClient.php
- src/Zendesk/API/Resources/ResourceAbstract.php
- src/Zendesk/API/Resources/Tags.php
- src/Zendesk/API/Resources/TicketComments.php
- src/Zendesk/API/Resources/Tickets.php
- src/Zendesk/API/Resources/Users.php
- src/Zendesk/API/Resources/Views.php
- src/Zendesk/API/UtilityTraits/InstantiatorTrait.php
- tests/Zendesk/API/UnitTests/BasicTest.php
- tests/Zendesk/API/UnitTests/DummyResource.php
- tests/Zendesk/API/UnitTests/ResourceTest.php
- tests/Zendesk/API/UnitTests/TicketCommentsTest.php
- tests/Zendesk/API/UnitTests/TicketsTest.php
- tests/Zendesk/API/UnitTests/UsersTest.php
- tests/Zendesk/API/UnitTests/ViewsTest.php
- tests/bootstrap.php
Added php codesniffer check to travis build. This will ensure we are following the PSR2 standard in our code.
Additionally made the build pass by using phpcbf (PHP Code Beautifier and Fixer) (https://github.com/squizlabs/PHP_CodeSniffer/wiki/Fixing-Errors-Automatically) to make our code PSR2 compliant.
- Jira link: https://zendesk.atlassian.net/browse/MI-95
- The travis builds might not pass (low)
> [MI-95] Add codesniffer to check for PSR2 standard to travis builds

- src/Zendesk/API/Resources/ResourceAbstract.php
- src/Zendesk/API/Resources/TicketAudits.php
- src/Zendesk/API/Resources/Tickets.php
- tests/Zendesk/API/UnitTests/TicketAuditsTest.php
Added ticket audits class and added tests
- Jira link: 
- The audit endpoint might not work correctly (low)
> Add ticket audits and ticket audits test

- composer.lock
- src/Zendesk/API/Http.php
- src/Zendesk/API/Resources/ResourceAbstract.php
- src/Zendesk/API/Resources/TicketForms.php
- src/Zendesk/API/Resources/Tickets.php
- src/Zendesk/API/Resources/Users.php
- src/Zendesk/API/Resources/Views.php
- tests/Zendesk/API/UnitTests/TicketFormsTest.php
Add the ticket forms resource and unit tests
> Add the ticket forms resource and unit tests

- src/Zendesk/API/HttpClient.php
- src/Zendesk/API/Resources/Macros.php
- src/Zendesk/API/Resources/ResourceAbstract.php
- tests/Zendesk/API/UnitTests/BasicTest.php
- tests/Zendesk/API/UnitTests/MacrosTest.php
Allow the client to access the macros resource
- Jira link: https://zendesk.atlassian.net/browse/MI-119
- Macros endpoints might not be called correctly (low)
> [MI-119] Add the macros resource

- src/Zendesk/API/Resources/TicketMetrics.php
- src/Zendesk/API/Resources/Tickets.php
- tests/Zendesk/API/UnitTests/TicketMetricsTest.php
Add TicketMetrics resource and unit test
> [MI-164] Add TicketMetrics resource and unit test

- src/Zendesk/API/HttpClient.php
- src/Zendesk/API/Resources/Automations.php
- tests/Zendesk/API/UnitTests/AutomationsTest.php
Add the automations resource so the client will be able to call automations endpoints
- Jira link: https://zendesk.atlassian.net/browse/MI-114
- We might not be able to call automations endpoints correctly
> [MI-114] Add automations resource

- .travis.yml
- src/Zendesk/API/HttpClient.php
- src/Zendesk/API/Resources/Triggers.php
- tests/Zendesk/API/UnitTests/TriggersTest.php
Add the triggers resource and allow usage of the trigger related endpoints
- Jira link: https://zendesk.atlassian.net/browse/MI-144
- We might not be able to call the trigger endpoints correctly (low)
> [MI-144] Allow client to use the Triggers resource

- src/Zendesk/API/HttpClient.php
- src/Zendesk/API/Resources/Groups.php
- src/Zendesk/API/Resources/ResourceAbstract.php
- src/Zendesk/API/Resources/Users.php
- tests/Zendesk/API/UnitTests/GroupsTest.php
Adds the Group resource and unit test
- Jira link: https://zendesk.atlassian.net/browse/MI-120
- None
> [MI-120] Allows the client to use the Groups resource

- src/Zendesk/API/Resources/ResourceAbstract.php
- src/Zendesk/API/Resources/UserIdentities.php
- src/Zendesk/API/Resources/Users.php
- tests/Zendesk/API/UnitTests/UserIdentitiesTest.php
Add the user identities resource
- Jira link: https://zendesk.atlassian.net/browse/MI-130
- We might not be able to call the user identity endpoint correctly (low)
> [MI-130] Add user Identities Resource

- src/Zendesk/API/HttpClient.php
- src/Zendesk/API/Resources/ResourceAbstract.php
- src/Zendesk/API/Resources/UserFields.php
- tests/Zendesk/API/UnitTests/ResourceTest.php
- tests/Zendesk/API/UnitTests/UserFieldsTest.php
* Add User Fields Resource
* Update get resource name from class to support camel cased classes
- Jira link: https://zendesk.atlassian.net/browse/MI-129
- We might not be able to access user fields endpoints with the client(medium)
> [MI-129] Add user fields resource

- src/Zendesk/API/HttpClient.php
- src/Zendesk/API/Resources/DynamicContent.php
- src/Zendesk/API/Resources/DynamicContentItemVariants.php
- src/Zendesk/API/Resources/DynamicContentItems.php
- src/Zendesk/API/UtilityTraits/ChainedParametersTrait.php
- tests/Zendesk/API/UnitTests/DynamicContentItemVariantsTest.php
Add resource for dynamic content items and variants, add tests for dynamic content item variants
- Jira link: 
- Medium - the client may not get the expected API response from dynamic_content/client and variant
> [MI-122] Dynamic Content

- src/Zendesk/API/HttpClient.php
- src/Zendesk/API/Resources/Organizations.php
- src/Zendesk/API/Resources/Users.php
- tests/Zendesk/API/UnitTests/OrganizationsTest.php
[MI-134] Allow the client to use the organizations resource
- Jira link: 
- Medium - the client may not get the expected API response
> [MI-134] Allow the client to use the organizations resource

- src/Zendesk/API/HttpClient.php
- src/Zendesk/API/Resources/Search.php
- tests/Zendesk/API/LiveTests/BasicTest.php
- tests/Zendesk/API/LiveTests/SearchTest.php
- tests/Zendesk/API/UnitTests/BasicTest.php
- tests/Zendesk/API/UnitTests/SearchTest.php
Add search endpoint and tests. Add authStrategy option to \LiveTests\BasicTest.
- Jira link: 
- Medium - The client might not send the query in the API's expected format.
> [MI-139] Add search endpoint and unit test

- src/Zendesk/API/HttpClient.php
- src/Zendesk/API/Resources/OrganizationSubscriptions.php
- src/Zendesk/API/Resources/Organizations.php
- src/Zendesk/API/Resources/Users.php
- tests/Zendesk/API/UnitTests/OrganizationSubscriptionsTest.php
Add organization subscriptions resource
- Jira link: https://zendesk.atlassian.net/browse/MI-136
- Medium - The client might call the wrong endpoint
> [MI-136] Add organization subscriptions resource

- src/Zendesk/API/BulkTraits/BulkDeleteTrait.php
- src/Zendesk/API/BulkTraits/BulkUpdateTrait.php
- src/Zendesk/API/Debug.php
- src/Zendesk/API/Http.php
- src/Zendesk/API/HttpClient.php
- src/Zendesk/API/Resources/Attachments.php
- src/Zendesk/API/Resources/AuditLogs.php
- src/Zendesk/API/Resources/DynamicContent.php
- src/Zendesk/API/Resources/DynamicContentItems.php
- src/Zendesk/API/Resources/Organizations.php
- src/Zendesk/API/Resources/ResourceAbstract.php
- src/Zendesk/API/Resources/TicketForms.php
- src/Zendesk/API/Resources/Tickets.php
- src/Zendesk/API/Resources/UserFields.php
- src/Zendesk/API/Resources/UserIdentities.php
- src/Zendesk/API/Resources/Users.php
- src/Zendesk/API/Resources/Views.php
- src/Zendesk/API/Utilities/Auth.php
- src/Zendesk/API/UtilityTraits/InstantiatorTrait.php
- tests/Zendesk/API/UnitTests/AuthTest.php
* Rename sendWithOptions to just send
* Fix getValidSubResources wrongly names child methods
* Cleanup method comments
* Better setting of debug information
* Add docblocks to methods missing docblocks
- Jira link: 
- Medium. There might be errors for misnamed methods
> Cleanup and refactor methods

- src/Zendesk/API/HttpClient.php
- src/Zendesk/API/Resources/Activities.php
- tests/Zendesk/API/UnitTests/ActivitiesTest.php
Add the activities resource so we can use the activities related endpoints using the client.
- Jira link: https://zendesk.atlassian.net/browse/MI-108
- Low. We might not be able to use the activities endpoints using the client
> [MI-108] Add activities resource

- src/Zendesk/API/Http.php
- src/Zendesk/API/HttpClient.php
- src/Zendesk/API/Resources/Attachments.php
- src/Zendesk/API/Resources/AuditLogs.php
- src/Zendesk/API/Resources/OrganizationFields.php
- src/Zendesk/API/Resources/TicketForms.php
- src/Zendesk/API/Resources/Tickets.php
- src/Zendesk/API/Resources/UserFields.php
- src/Zendesk/API/Resources/UserIdentities.php
- src/Zendesk/API/Resources/Users.php
- src/Zendesk/API/Resources/Views.php
- tests/Zendesk/API/UnitTests/ResourceTest.php
- tests/Zendesk/API/UnitTests/TicketsTest.php
Move clearing of sideload to every request made to reduce repeating code
* JIRA:
* Low. Sideloading might not work
> Move clearing of sideload to send utility method

- README.md
Add the coding standard psr2 to the readme
* JIRA: https://zendesk.atlassian.net/browse/MI-171
* None
> [MI-171] Add coding standard to readme

- src/Zendesk/API/HttpClient.php
- src/Zendesk/API/Resources/Organizations.php
- src/Zendesk/API/Resources/RequestComments.php
- src/Zendesk/API/Resources/Requests.php
- src/Zendesk/API/Resources/Users.php
- tests/Zendesk/API/UnitTests/BasicTest.php
- tests/Zendesk/API/UnitTests/RequestCommentsTest.php
- tests/Zendesk/API/UnitTests/RequestsTest.php
Add the requests resource
* JIRA: https://zendesk.atlassian.net/browse/MI-118
* Low. We might not be able to access the resource endpoints using the client
> [MI-118] Add Requests resource

- src/Zendesk/API/HttpClient.php
- src/Zendesk/API/Resources/TicketImports.php
- tests/Zendesk/API/UnitTests/TicketImportsTest.php
Add resource for importing tickets
* JIRA: https://zendesk.atlassian.net/browse/MI-117
* Low. We might not be able to use the ticket import endpoints.
> [MI-117] Add ticket imports resource

- src/Zendesk/API/HttpClient.php
- src/Zendesk/API/Resources/Locales.php
- tests/Zendesk/API/UnitTests/BasicTest.php
- tests/Zendesk/API/UnitTests/LocalesTest.php
Add the Locales resource to call locales endpoints
* JIRA: https://zendesk.atlassian.net/browse/MI-125
* Low. We might not be able to call the locales endpoints
> [MI-125] Add Locales Resource

- src/Zendesk/API/HttpClient.php
- src/Zendesk/API/Resources/CustomRoles.php
- tests/Zendesk/API/UnitTests/CustomRolesTest.php
Add Custom Agent Roles resource and test
- Jira link: https://zendesk.atlassian.net/browse/MI-128
- Low. We might not be able to call the Custom Roles endpoint using the client.
> [MI-128] Custom Agent Roles

- README.md
- src/Zendesk/API/Traits/Utility/InstantiatorTrait.php
Add traits usage to readme
- Jira link: https://zendesk.atlassian.net/browse/MI-170
- None
> [MI-170] Add traits usage to readme

- src/Zendesk/API/HttpClient.php
- src/Zendesk/API/Resources/GroupMemberships.php
- src/Zendesk/API/Resources/Groups.php
- src/Zendesk/API/Resources/Users.php
- tests/Zendesk/API/UnitTests/GroupMembershipsTest.php
- tests/Zendesk/API/UnitTests/OrganizationMembershipsTest.php
[MI-123] 
Add group memberships resource and test
- Jira link: https://zendesk.atlassian.net/browse/MI-123
- Low. We might not be able to call the group memberships endpoints
> [MI-123] Add group memberships resource and test

- src/Zendesk/API/HttpClient.php
- src/Zendesk/API/Resources/AppInstallations.php
- tests/Zendesk/API/UnitTests/AppInstallationsTest.php
Adds the App Installations resource and tests
- Jira link: https://zendesk.atlassian.net/browse/MI-109
- Medium - The client might not be able to connect to the endpoint
> [MI-109] App installations

- src/Zendesk/API/HttpClient.php
- src/Zendesk/API/Resources/Incremental.php
- src/Zendesk/API/Resources/IncrementalExports.php
- tests/Zendesk/API/UnitTests/IncrementalExportsTest.php
Add resource for incremental export endpoints
* JIRA: https://zendesk.atlassian.net/browse/MI-113
* Low. You might not be able to call the incremental export endpoints
> [MI-113] Add incremental exports resource

- src/Zendesk/API/HttpClient.php
- src/Zendesk/API/Resources/Autocomplete.php
- tests/Zendesk/API/UnitTests/AutocompleteTest.php
Add autocomplete resource which will allow us to use the autocompletion endpoints
* JIRA: https://zendesk.atlassian.net/browse/MI-113
* Low. We might not be able to use the autocompletion endpoints
> [MI-113] Add autocompletion resource

- src/Zendesk/API/HttpClient.php
- src/Zendesk/API/Resources/Brands.php
- src/Zendesk/API/Resources/Users.php
- tests/Zendesk/API/UnitTests/BasicTest.php
- tests/Zendesk/API/UnitTests/BrandsTest.php
Add brands resource so we can use the brands endpoints using the client
* JIRA: https://zendesk.atlassian.net/browse/MI-131
* Low. We might not be able to access the brands endpoints using the client
> [MI-131] Add brands resource

- src/Zendesk/API/HttpClient.php
- src/Zendesk/API/Resources/SatisfactionRatings.php
- tests/Zendesk/API/UnitTests/SatisfactionRatingsTest.php
Add satisfaction ratings resource
* JIRA: https://zendesk.atlassian.net/browse/MI-138
* Low. We might not be able to access the satisfaction ratings endpoints
> [MI-138] Add satisfaction ratings resource

- src/Zendesk/API/HttpClient.php
- src/Zendesk/API/Resources/SharingAgreements.php
- tests/Zendesk/API/UnitTests/SharingAgreementsTest.php
Add the sharing agreements resource
* JIRA: https://zendesk.atlassian.net/browse/MI-140
* Low. We might not be able to call the sharing agreement endpoints using the client
> [MI-140] Add the sharing agreements resource

- src/Zendesk/API/HttpClient.php
- src/Zendesk/API/Resources/SuspendedTickets.php
- tests/Zendesk/API/UnitTests/SuspendedTicketsTest.php
Add the suspended tickets resource
* JIRA: https://zendesk.atlassian.net/browse/MI-142
* Low. We might not be able to call the suspended tickets endpoints
> [MI-142] Add the suspended tickets resource

- src/Zendesk/API/HttpClient.php
- src/Zendesk/API/Resources/SupportAddresses.php
- tests/Zendesk/API/UnitTests/SupportAddressesTest.php
Add support address resource and test
- Jira link: https://zendesk.atlassian.net/browse/MI-141
- Low. We might not be able to use the support address resources
> [MI-141] Support Address

- src/Zendesk/API/HttpClient.php
- src/Zendesk/API/Resources/SlaPolicies.php
- tests/Zendesk/API/UnitTests/SlaPoliciesTest.php
Add the SLA policies resource and test case
* JIRA: https://zendesk.atlassian.net/browse/MI-151
* Low. We might not be able to call the sla policies endpoints using the client
> [MI-151] Add the SLA Policies resource

- src/Zendesk/API/HttpClient.php
- src/Zendesk/API/Resources/Sessions.php
- src/Zendesk/API/Resources/Users.php
- tests/Zendesk/API/UnitTests/SessionsTest.php
Add sessions resource and test.
Describe your PR
- Jira link: https://zendesk.atlassian.net/browse/MI-149
- Low - the client might not be able to access the sessions endpoint
> [MI-149] Sessions

- src/Zendesk/API/HttpClient.php
- src/Zendesk/API/Resources/Apps.php
- src/Zendesk/API/Resources/Brands.php
- src/Zendesk/API/Resources/Users.php
- src/Zendesk/API/Traits/Resource/MultipartUpload.php
- tests/Zendesk/API/UnitTests/AppsTest.php
- tests/Zendesk/API/UnitTests/DummyResource.php
- tests/Zendesk/API/UnitTests/ResourceTest.php
Add the Apps resource
* JIRA: https://zendesk.atlassian.net/browse/MI-110
* Low. We might not be able to use the apps resources
> [MI-110] Add the Apps Resource

- src/Zendesk/API/HttpClient.php
- src/Zendesk/API/Resources/HelpCenter/Categories.php
- src/Zendesk/API/Resources/Voice.php
- src/Zendesk/API/Resources/Voice/PhoneNumbers.php
- src/Zendesk/API/Resources/Voice/ResourceAbstract.php
- tests/Zendesk/API/UnitTests/Core/AppsTest.php
- tests/Zendesk/API/UnitTests/Voice/PhoneNumbersTest.php
Add Voice > Phone Numbers resource and test.
- Jira link: https://zendesk.atlassian.net/browse/MI-163
- Medium - the client may not be able to access the /channels/voice/phone_numbers endpoint
> [MI-163] Voice - Phone Numbers

- src/Zendesk/API/HttpClient.php
- src/Zendesk/API/Resources/Bookmarks.php
- src/Zendesk/API/Resources/Core/Bookmarks.php
- tests/Zendesk/API/UnitTests/BookmarksTest.php
Add the bookmarks resource
* JIRA: https://zendesk.atlassian.net/browse/MI-148
* Low. We might not be able to call the bookmark endpoints using the client
> Add bookmarks resource

- src/Zendesk/API/HttpClient.php
- src/Zendesk/API/Resources/AppLocations.php
- src/Zendesk/API/Resources/Core/AppInstallations.php
- src/Zendesk/API/Resources/Core/AppLocations.php
- src/Zendesk/API/Resources/Core/Apps.php
- tests/Zendesk/API/UnitTests/AppLocationsTest.php
:haircut: ~~waiting for #144~~
Add support address resource and test
- Jira link: https://zendesk.atlassian.net/browse/MI-147
- Low. We might not be able to use the App Locations resources
> [MI-147] App Locations

- src/Zendesk/API/Http.php
- src/Zendesk/API/HttpClient.php
- tests/Zendesk/API/UnitTests/BasicTest.php
- tests/Zendesk/API/UnitTests/Core/ResourceTest.php
- tests/Zendesk/API/UnitTests/Core/UsersTest.php
Add User-Agent header to API calls
Describe your PR
- Jira link: https://zendesk.atlassian.net/browse/MI-180
- Low - the User-Agent header might not be sent to the API
> [MI-180] Add User-Agent header to API calls

- README.md
Update Readme to let users know that v2 is now merged and in beta
* JIRA: https://zendesk.atlassian.net/browse/MI-178
* None
> [MI-178] Update Readme to let users know that v2 is now merged and in beta

- README.md
- composer.json
- composer.lock
- src/Zendesk/API/Exceptions/ApiResponseException.php
- src/Zendesk/API/Resources/Core/Tickets.php
- src/Zendesk/API/Resources/Core/Users.php
- tests/Zendesk/API/LiveTests/AuthTest.php
- tests/Zendesk/API/LiveTests/TicketsTest.php
- tests/Zendesk/API/LiveTests/UsersTest.php
- tests/Zendesk/API/UnitTests/Core/UsersTest.php
Add live tests for user and ticket operations
* JIRA: https://zendesk.atlassian.net/browse/MI-192
* Low. Set password might not work properly
> Add live tests for tickets and users

- composer.json
Add version to composer.json file
* JIRA:
* None
> Add version to composer.json file

- README.md
- index.php
When merging in the v2 branch we forgot to update the readme file to reference the new HTTPClient and auth which is used.
/cc @joseconsador @miogalang 
- The examples might actually work :)
> Update readme and example to use the new auth style

- README.md
@miogalang @joseconsador further readme updates
> Update readme documentation for update and delete

- README.md
Add pagination instructions to the readme
/cc @jwswj @joseconsador @mmolina
* JIRA: https://zendesk.atlassian.net/browse/MI-211
* Low. We might have wrong documentation
> [MI-211] Add pagination instructions to the readme

- src/Zendesk/API/HttpClient.php
change method name to tickets() to conform to the list of valid sub resources
> change method name to tickets()

- README.md
Link to the upgrade guide from v1 to v2
/cc @jwswj @joseconsador @iandjx @pdeuter @mmolina
* JIRA: https://zendesk.atlassian.net/browse/MI-289
* Low. The readme might give the wrong info
> [MI-289] Mention the upgrade guide in the project readme

- .travis.yml
Fix the notifications for the travis build
/cc @zendesk/butanding @mmolina 
* JIRA: 
* Low. Notification of builds might not be sent out
> Change notifications for the travis build

- README.md
- src/Zendesk/API/Resources/Core/DynamicContentItemVariants.php
- src/Zendesk/API/Resources/Core/Organizations.php
- src/Zendesk/API/Resources/Core/Tickets.php
- src/Zendesk/API/Resources/Core/Users.php
- src/Zendesk/API/Traits/Resource/CreateOrUpdateMany.php
- tests/Zendesk/API/LiveTests/UsersTest.php
- tests/Zendesk/API/UnitTests/Core/DummyResource.php
Currently there is no way to use the createOrUpdate API call.
> Add CreateOrUpdate as a new way of updating Users

- README.md
@miogalang @joseconsador @iandjx
> The API client has been out of beta for a while

- README.md
- samples/getTickets.php
- samples/oauth.php
- src/Zendesk/API/HttpClient.php
HttpClient->username is not used, so no need to pass $username on construction
> eliminate username property

- README.md
/cc @zendesk/mintegrations @miketineo @mmolina 
Add additional badges to readme
* low. Readme might not render correctly
> Add badges for stable version, downloads, and license

- src/Zendesk/API/Resources/Core/AppInstallations.php
- tests/Zendesk/API/UnitTests/Core/AppInstallationsTest.php
Fix the create and update endpoints in app installations to have to correct parameters
* JIRA: https://zendesk.atlassian.net/browse/MI-755
* low. We might not be able to install an app or update an app installation
> [MI-755] Fix update and create for app installations

- composer.json
- composer.lock
Update the guzzle version requirement
* low. We might not have the right version of guzzle
> Update guzzle version requirement to be less restrictive

- src/Zendesk/API/Http.php
- src/Zendesk/API/HttpClient.php
- src/Zendesk/API/Resources/Embeddable.php
- src/Zendesk/API/Resources/Embeddable/ConfigSets.php
- src/Zendesk/API/Resources/Embeddable/ResourceAbstract.php
- src/Zendesk/API/Resources/ResourceAbstract.php
- tests/Zendesk/API/UnitTests/BasicTest.php
- tests/Zendesk/API/UnitTests/Embeddable/ConfigSetsTest.php
Create API client resource for the embeddable config_set create (`POST: /embeddable/api/config_sets.json`) and update (`PUT: /embeddable/api/config_sets/{$id}.json`) endpoints.
* JIRA: https://zendesk.atlassian.net/browse/MI-811
* [HIGH] This essentially touches all the API calls due to the modified api base path implementation
> [MI-811] Create embeddable config_sets resource

- src/Zendesk/API/Resources/Core/UserTickets.php
- src/Zendesk/API/Resources/Core/Users.php
- tests/Zendesk/API/UnitTests/Core/UserTicketsTest.php
Add in user specific ticket endpoints:
GET /api/v2/users/{user_id}/tickets/requested.json
GET /api/v2/users/{user_id}/tickets/ccd.json
GET /api/v2/users/{user_id}/tickets/assigned.json
> Add in user specific ticket endpoints.

- src/Zendesk/API/HttpClient.php
- src/Zendesk/API/Resources/Core/AppInstallations.php
- src/Zendesk/API/Resources/Core/AuditLogs.php
- src/Zendesk/API/Resources/Core/OrganizationTickets.php
- src/Zendesk/API/Resources/Core/Organizations.php
- src/Zendesk/API/Resources/Core/Sessions.php
- src/Zendesk/API/Resources/Core/SlaPolicies.php
- src/Zendesk/API/Resources/Core/TicketAudits.php
- src/Zendesk/API/Resources/Core/TicketComments.php
- src/Zendesk/API/Resources/Core/TicketForms.php
- src/Zendesk/API/Resources/Core/Tickets.php
- src/Zendesk/API/Resources/Core/UserIdentities.php
- src/Zendesk/API/Resources/Core/Users.php
- src/Zendesk/API/Resources/Core/Views.php
- src/Zendesk/API/Resources/HelpCenter/Articles.php
- src/Zendesk/API/Resources/ResourceAbstract.php
- src/Zendesk/API/Resources/Voice/PhoneNumbers.php
- src/Zendesk/API/Traits/Resource/Create.php
- src/Zendesk/API/Traits/Resource/CreateMany.php
- src/Zendesk/API/Traits/Resource/Delete.php
- src/Zendesk/API/Traits/Resource/DeleteMany.php
- src/Zendesk/API/Traits/Resource/Find.php
- src/Zendesk/API/Traits/Resource/Locales.php
- src/Zendesk/API/Traits/Resource/MultipartUpload.php
- src/Zendesk/API/Traits/Resource/Update.php
- src/Zendesk/API/Traits/Utility/ChainedParametersTrait.php
- src/Zendesk/API/Traits/Utility/InstantiatorTrait.php
- src/Zendesk/API/Utilities/Auth.php
- src/Zendesk/API/Utilities/OAuth.php
No functional changes were made.  This is general code cleanup that falls into 4 categories:
1) Fix obvious typos
2) Add missing imports
3) Remove unused imports
4) Fix phpDoc documentation.
> General cleanup

- README.md
- Get all users.
- Retrieve tickets by a end-user
> Added 2 new examples

- index.php
- samples/tickets/getTicketComments.php
**getTicketcomments.php** This sample shows how you can get all comments from a related ticket.
Added a new link for **getTicketcomments.php**
> #272 - Added example for comments

- README.md
- index.php
- samples/tickets/createTicketWithAttachment.php
Added **creation of tickets with attachment** on readme and sample
* Issue: https://github.com/zendesk/zendesk_api_client_php/issues/263
* none
> Creation of tickets with attachment on readme and sample

- src/Zendesk/API/HttpClient.php
> Version bump

- src/Zendesk/API/Resources/Core/Users.php
- tests/Zendesk/API/UnitTests/Core/UsersTest.php
Tried to fix #308 without breaking backward compatibility
> Fix user's merge function

- index.php
- samples/attachments/uploadFileAttachment.php
- samples/attachments/uploadStreamAttachment.php
- src/Zendesk/API/Resources/Core/Attachments.php
- src/Zendesk/API/Traits/Resource/MultipartUpload.php
Add samples for attachments and some minor variable improvement to the attachment resource.
* [low] Could mess up file stream upload, not likely.
> Add samples for uploading attachment

- src/Zendesk/API/Resources/HelpCenter.php
Hey, I have added missing dockblock for missing method.
> Added missing dockblock for articles() method

- src/Zendesk/API/Resources/HelpCenter/Articles.php
- src/Zendesk/API/Traits/Resource/Search.php
- tests/Zendesk/API/UnitTests/Core/AppInstallationsTest.php
- tests/Zendesk/API/UnitTests/HelpCenter/ArticlesTest.php
* HelpCenter Articles Search endpoint made available
* **DO NOT MERGE**
* Wait for April Feature freeze to end before merging and then reply to [support ticket](https://support.zendesk.com/agent/tickets/2531797)
* JIRA: https://zendesk.atlassian.net/browse/MI-1528
* [low] endpoint returns a 404 status code if the user did not activate his helpcenter yet
> [MI-1528] HelpCenter Articles Search

- src/Zendesk/API/Resources/HelpCenter.php
- src/Zendesk/API/Resources/HelpCenter/Sections.php
- tests/Zendesk/API/UnitTests/HelpCenter/SectionsTest.php
This change adds support of the sections area of the help center.
> Implemented support of sections in help center

- samples/organizations/createOrganization
- samples/organizations/createOrganization.php
cleaning up my previous (poor) attempt at submitting this example:
https://github.com/zendesk/zendesk_api_client_php/pull/294
I believe I've addressed your style comments, and while working with SMichaels he recommended creating a fresh PR which I'm doing here. (closing 294)
> add Organization creation example

- src/Zendesk/API/Traits/Resource/FindAll.php
As defined in https://github.com/zendesk/zendesk_api_client_php/blob/a37cd908c62627adc27b3f4c0c261ff8bbf29a7d/src/Zendesk/API/HttpClient.php#L447-L448
> Add missing @throws annotations

- phpunit.xml.dist
/cc @zendesk/pegasus 
Removed secrets and tokens from the repo. There will be a separate PR to remove the commit histories. 
* Support Ticket:  https://support.zendesk.com/agent/tickets/4532782
* [medium] Not entirely familiar with the repo, however the tokens are used for unit testing so it should not break any live functionalities.
> Remove secrets and tokens from repo

- src/Zendesk/API/Resources/Core/Attachments.php
see https://github.com/zendesk/zendesk_api_client_php/blob/62e1f8488a78694fa88fe4c084a8c485a55f2824/src/Zendesk/API/Resources/Core/Attachments.php#L69-L71
> Fixed PHP Doc of Attachments::upload()

- composer.lock
Upgrade phpmd to latest version
> Upgrade phpmd to latest version 

- src/Zendesk/API/Resources/Core/Webhooks.php
Fix https://github.com/zendesk/zendesk_api_client_php/issues/497
Fix delete endpoint for webhooks
> feat: fix delete webhook

- README.md
We will no longer be supporting this package
> Deprecate support

- src/Zendesk/API/Resources/Core/Users.php
to be able to do
`$client->users($userId)->tags()->create()`
> add tags resource for Resource\Core\Users to work with user tags

- src/Zendesk/API/Resources/Core/DynamicContentItemVariants.php
Also adds the UPDATE method
Fixes #409
> DynamicContentItemVariants: Fix objectName variables

- src/Zendesk/API/HttpClient.php
Add the optional `$id` param in `organizations()` method definition.  Param used in `OrganizationTicketsTest.php` L20
> Updating organizations() method definition
